spring:
  application:
    name: ordering_system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_test_program?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 1q2w3e4r%T
server:
  port: 8088
#SpringBoot整合Mybatis配置
mybatis:
  type-aliases-package: com.yidong.ordering.entity
  mapper-locations: classpath:/mapper/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true



